events {
}
http {
    server {
        listen 80;
        listen [::]:80;
        server_name dodo.localhost;

        set $api_target "http://dodo-server:8283";
        set $portal_target "http://dodo-portal:80";
        
        # Route API and WebSocket requests to backend
        location /v1/ {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # WebSocket support
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            
            resolver 127.0.0.11; # docker dns
            proxy_pass $api_target;
        }

        # Route all other static/page traffic to frontend portal
        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            resolver 127.0.0.11; # docker dns
            proxy_pass $portal_target;
        }
    }

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }
}
