@echo off
REM Generated by trunk tool 'black'
set HOME=%HOME%
if not defined HOME set HOME=
set PATH=C:\Users\Praveen P\AppData\Local\trunk\tools\black\26.3.1-eca9c633f4e65d6c66d4a90c9eecc64e/bin;C:\Users\Praveen P\AppData\Local\trunk\tools\black\26.3.1-eca9c633f4e65d6c66d4a90c9eecc64e/Scripts;C:\Users\Praveen P\AppData\Local\trunk\tools\python\3.14.4-cb3a144a569cdde1b1583669bb421ff0/bin;C:\Users\Praveen P\AppData\Local\trunk\tools\python\3.14.4-cb3a144a569cdde1b1583669bb421ff0;C:\Users\Praveen P\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Praveen P\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set PYTHONUTF8=1
set VIRTUAL_ENV=C:\Users\Praveen P\AppData\Local\trunk\tools\black\26.3.1-eca9c633f4e65d6c66d4a90c9eecc64e

start /w /b black %*
