@echo off
REM Generated by trunk tool 'isort'
set HOME=%HOME%
if not defined HOME set HOME=
set PATH=C:\Users\Praveen P\AppData\Local\trunk\tools\isort\8.0.1-9c11fdf4ae336bdec08bb71a63fd85d6/bin;C:\Users\Praveen P\AppData\Local\trunk\tools\isort\8.0.1-9c11fdf4ae336bdec08bb71a63fd85d6/Scripts;C:\Users\Praveen P\AppData\Local\trunk\tools\python\3.14.4-cb3a144a569cdde1b1583669bb421ff0/bin;C:\Users\Praveen P\AppData\Local\trunk\tools\python\3.14.4-cb3a144a569cdde1b1583669bb421ff0;C:\Users\Praveen P\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Praveen P\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set PYTHONUTF8=1
set VIRTUAL_ENV=C:\Users\Praveen P\AppData\Local\trunk\tools\isort\8.0.1-9c11fdf4ae336bdec08bb71a63fd85d6

start /w /b isort %*
