@echo off
REM Generated by trunk tool 'svgo'
set NODE_PATH=C:\Users\Praveen P\AppData\Local\trunk\tools\svgo\4.0.1-b749270fd7c7f369fdca68eb8725558c/node_modules
set PATH=C:\Users\Praveen P\AppData\Local\trunk\tools\svgo\4.0.1-b749270fd7c7f369fdca68eb8725558c/node_modules/.bin;C:\Users\Praveen P\AppData\Local\trunk\tools\node\22.16.0-12da8a4c27b144aedaf7d975e067667c/bin;C:\Users\Praveen P\AppData\Local\trunk\tools\node\22.16.0-12da8a4c27b144aedaf7d975e067667c;C:\Users\Praveen P\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Praveen P\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%
set HOME=%HOME%
if not defined HOME set HOME=

start /w /b svgo %*
