@echo off
REM Generated by trunk tool 'taplo'
set PATH=C:\Users\Praveen P\AppData\Local\trunk\tools\taplo\0.10.0-257e74fb8eb845f6609992399b575a2b;C:\Users\Praveen P\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Praveen P\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b taplo %*
