@echo off
REM Generated by trunk tool 'trufflehog'
set PATH=C:\Users\Praveen P\AppData\Local\trunk\tools\trufflehog\3.95.2-36bcc14609bbca66fd416427f6bab1b8;C:\Users\Praveen P\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/bin;C:\Users\Praveen P\AppData\Local\trunk\tools\git-bash\2.40.1-da0c3e1526d36e62bf43d06ec46c5052/usr/bin;%PATH%

start /w /b trufflehog %*
