"""add circuit breaker states table

Revision ID: 338b905379b9
Revises: 1c28e167b74f
Create Date: 2026-05-22 22:46:41.659725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '338b905379b9'
down_revision: Union[str, None] = '1c28e167b74f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


try:
    from dodo.orm.custom_columns import CommonVector
except ImportError:
    CommonVector = sa.BLOB


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('circuit_breaker_states',
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(), nullable=False),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('last_failure_at', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('(FALSE)'), nullable=False),
    sa.Column('_created_by_id', sa.String(), nullable=True),
    sa.Column('_last_updated_by_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('handle', 'id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('circuit_breaker_states')
    # ### end Alembic commands ###

