"""add password_hash to users

Revision ID: e1f9a4ad8f04
Revises: 338b905379b9
Create Date: 2026-05-28 10:39:58.348769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import dodo



# revision identifiers, used by Alembic.
revision: str = 'e1f9a4ad8f04'
down_revision: Union[str, None] = '338b905379b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###

